name: Bridgecrew
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        directory: terraform/
  image-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: 'docker pull nginx:1.17.9-alpine'
    - name: BC Image Scan
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        docker-image: nginx:1.17.9-alpine
        dockerfile-path: /terraform/aws/resources/Dockerfile
